In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name":          ["Ali","Sara","Raj","Mia","Tom","Zoe"],
    "math_score":    [88, 72, 95, 61, 84, 77],
    "english_score": [75, 90, 68, 85, 79, 92],
    "age":           [20, 21, 20, 22, 21, 20]
})

mean_maths = np.mean([df["math_score"]])
std_maths = np.std([df["math_score"]])
print(mean_maths, std_maths)

79.5 11.086778913041726


In [11]:
df["total_scores"] = df['math_score'] + df['english_score']

df["grade"] = df['total_scores'].apply(lambda x: 'A' if x>= 160 else 'B')
print(df['grade'])


0    A
1    A
2    A
3    B
4    A
5    A
Name: grade, dtype: str


In [19]:
scores = df[["math_score","english_score"]].values

normalised = (scores - scores.min(axis=0)) / (scores.max(axis=0) - scores.min(axis=0))

df["math_norm"] = normalised[:, 0]
df["english_norm"] = normalised[:, 1]

print(df[["english_norm", "math_norm"]])

   english_norm  math_norm
0      0.291667   0.794118
1      0.916667   0.323529
2      0.000000   1.000000
3      0.708333   0.000000
4      0.458333   0.676471
5      1.000000   0.470588


In [32]:
df2 = pd.DataFrame({
    "name":          ["Ali","Sara","Raj","Mia","Tom"],
    "math_score":    [88, np.nan, 95, np.nan, 84],
    "english_score": [75, 90, np.nan, 85, 79]
})

print(df2.isnull().sum())

df2["math_score"] = df2["math_score"].fillna(df2["math_score"].mean())

df2 = df2.dropna(subset=["english_score"])
print(df2)

name             0
math_score       2
english_score    1
dtype: int64
   name  math_score  english_score
0   Ali        88.0           75.0
1  Sara        89.0           90.0
3   Mia        89.0           85.0
4   Tom        84.0           79.0


## Revision

In [33]:
df = pd.DataFrame({
    "name":          ["Ali","Sara","Raj","Mia","Tom","Zoe"],
    "math_score":    [88, 72, 95, 61, 84, 77],
    "english_score": [75, 90, 68, 85, 79, 92],
    "age":           [20, 21, 20, 22, 21, 20]
})

mean_math = np.mean(df["math_score"])
std_math = np.std(df["math_score"])

print(mean_math, std_math)

79.5 11.086778913041726


In [50]:
scores = df[["math_score", "english_score"]].values
print(scores)

normalized = (scores - scores.min(axis=0)) / (scores.max(axis=0) - scores.min(axis=0))

df["math_norm"] = normalized[:, 0]
df["english_norm"] = normalized[:, 1]

print(df[["english_norm", "math_norm"]])

[[88 75]
 [72 90]
 [95 68]
 [61 85]
 [84 79]
 [77 92]]
   english_norm  math_norm
0      0.291667   0.794118
1      0.916667   0.323529
2      0.000000   1.000000
3      0.708333   0.000000
4      0.458333   0.676471
5      1.000000   0.470588


In [54]:
df["total_score"] = df["math_score"] + df["english_score"]

df["grade"] = df["total_score"].apply(lambda x: "A" if x>=160  else "B")
print(df[["name", "total_score", "grade"]])

   name  total_score grade
0   Ali          163     A
1  Sara          162     A
2   Raj          163     A
3   Mia          146     B
4   Tom          163     A
5   Zoe          169     A


In [56]:
df2 = pd.DataFrame({
    "name":          ["Ali","Sara","Raj","Mia","Tom"],
    "math_score":    [88, np.nan, 95, np.nan, 84],
    "english_score": [75, 90, np.nan, 85, 79]
})

print(df2.isnull().count())

df2["math_score"] = df2["math_score"].fillna(df2["math_score"].mean())
print(df2["math_score"])

df2 = df2.dropna(subset=["math_score", "english_score"])
print(df2)

name             5
math_score       5
english_score    5
dtype: int64
0    88.0
1    89.0
2    95.0
3    89.0
4    84.0
Name: math_score, dtype: float64
   name  math_score  english_score
0   Ali        88.0           75.0
1  Sara        89.0           90.0
3   Mia        89.0           85.0
4   Tom        84.0           79.0


In [61]:
data = df[["math_score", "english_score", "age"]].values
print(data)

corr_matrix = np.corrcoef(data.T)
print(corr_matrix)

[[88 75 20]
 [72 90 21]
 [95 68 20]
 [61 85 22]
 [84 79 21]
 [77 92 20]]
[[ 1.         -0.76849733 -0.80675117]
 [-0.76849733  1.          0.34518681]
 [-0.80675117  0.34518681  1.        ]]
